mixed-port: 7890
allow-lan: true
authentication:
  - "Bisher:4TctiiWzSCi%6ij4"
tcp-concurrent: true
enable-process: true
find-process-mode: always
mode: rule
log-level: debug
ipv6: true
keep-alive-interval: 30
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
    TLS:
      ports:
        - 443
        - 8443
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
  strict-route: true
  route-exclude-address:
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 169.254.0.0/16
    - 224.0.0.0/4
    - 255.255.255.255/32
  mtu: 1500

dns:
  enable: true
  ipv6: true
  use-hosts: false
  use-system-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "geosite:private"               # Все локальные домены
  - "geosite:connectivity-check"    # Все домены для проверки подключения
  - "geosite:category-ntp"          # Все NTP-серверы
  - "+.stun.l.google.com"           # STUN (WebRTC / VoIP)
  - "*.stun.*.*"
  - "*.turn.*.*"
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - "+.stun.telegram.org"           
  cache-algorithm: arc # Улучшает производительность кэша
  respect-rules: true # DNS-запросы не проходят через прокси, что ускоряет их

  default-nameserver: # DNS для первичных доменов напрямую
    - tls://77.88.8.8#DIRECT # Yandex DNS over TLS
    - 195.208.4.1#DIRECT # НСДИ
    - system
  proxy-server-nameserver: # DNS для первичных доменов прокси
    - tls://9.9.9.11#DIRECT  # Quad9 DNS over TLS
    - tls://8.8.8.8#DIRECT   # Google DNS over TLS
    - system

  direct-nameserver: # DNS напрямую
    - common.dot.dns.yandex.net#DIRECT # Yandex DNS over TLS
    - system
  nameserver: # DNS для прокси
    - https://cloudflare-dns.com/dns-query#🌍 Блокированное
    

  fallback: # Запасные DNS при отказе основных
    - https://doh.opendns.com/dns-query
    - https://dns.google/dns-query

proxies:

proxy-providers:
  pirozhenka-fun-jwl3o:
    type: http
    url: 'https://pirozhenka.fun:2096/subBisher/43nqusslcc16styl'
    interval: 3600
    path: ./providers/pirozhenka-fun-jwl3o.yaml
    health-check:
      enable: true
      lazy: true
      url: 'http://www.gstatic.com/generate_204'
      interval: 600

proxy-groups:
  - name: 🌍 Блокированное
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png
    type: select
    include-all: true
    proxies:
      - ⚡️ Быстрейший
      # LEAVE THIS LINE!
  - name: • YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    include-all: true
    proxies:
      - ⚡️ Быстрейший
      - DIRECT
      # LEAVE THIS LINE!
  - name: • Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    include-all: true
    proxies:
      - ⚡️ Быстрейший
      - DIRECT
      # LEAVE THIS LINE!
  - name: • Discord
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    type: select
    include-all: true
    proxies:
      - ⚡️ Быстрейший
      - DIRECT
      # LEAVE THIS LINE!
  - name: • Steam
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    type: select
    include-all: true
    proxies:
      - DIRECT
      - ⚡️ Быстрейший
      # LEAVE THIS LINE!
  - name: ⚡️ Быстрейший
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    tolerance: 50  # задержка в мс, что бы не переключаться между серверами слишком часто
    url: https://captive.apple.com/generate_204
    hidden: true
    interval: 300
    include-all: true
    proxies:
      # LEAVE THIS LINE!
  - name: Россия
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Russia.png
    type: select
    include-all: true
    proxies:
      - DIRECT
      - ⚡️ Быстрейший
      # LEAVE THIS LINE!
  - name: 🌐 Остальное
    type: select
    include-all: true
    proxies:
      - DIRECT
      - ⚡️ Быстрейший
      # LEAVE THIS LINE!

rule-providers:
  ru-inline-banned:
    type: http
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/inline/ru-inline-banned.yaml
    interval: 86400
    behavior: classical
    format: yaml
    path: ./rule-sets/ru-inline-banned.yaml
  ru-inline:
    type: http
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/inline/ru-inline.yaml
    interval: 86400
    behavior: classical
    format: yaml
    path: ./rule-sets/ru-inline.yaml
  ru-app-list:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/legiz-ru/mihomo-rule-sets/main/other/ru-app-list.yaml
    path: ./rule-sets/ru-app-list.yaml
    interval: 86400
  games-direct:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/games-direct.yaml
    path: ./rule-sets/games-direct.yaml
    interval: 86400
  torrent-trackers:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-trackers.mrs
    path: ./rule-sets/torrent-trackers.mrs
    interval: 86400
  torrent-clients:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-clients.yaml
    path: ./rule-sets/torrent-clients.yaml
    interval: 86400
  geosite-ru:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ru.mrs
    path: ./geosite-ru.mrs
    interval: 86400
  xiaomi:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/xiaomi.mrs
    path: ./rule-sets/xiaomi.mrs
    interval: 86400
  blender:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/blender.mrs
    path: ./rule-sets/blender.mrs
    interval: 86400
  drweb:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/drweb.mrs
    path: ./rule-sets/drweb.mrs
    interval: 86400
  debian:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/debian.mrs
    path: ./rule-sets/debian.mrs
    interval: 86400
  canonical:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/canonical.mrs
    path: ./rule-sets/canonical.mrs
    interval: 86400
  python:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/python.mrs
    path: ./rule-sets/python.mrs
    interval: 86400
  geoip-ru:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/ru.mrs
    path: ./geoip-ru.mrs
    interval: 86400
  geosite-private:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/private.mrs
    path: ./geosite-private.mrs
    interval: 86400
  geoip-private:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/private.mrs
    path: ./geoip-private.mrs
    interval: 86400
  ads:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ads-all.mrs
    path: ./category-ads-all.mrs
    interval: 86400
  youtube:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/youtube.mrs
    path: ./youtube.mrs
    interval: 86400
  ru-blocked:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/mrs/ru-blocked.mrs
    path: ./rule-sets/ru-blocked.mrs
    interval: 86400
  ru-blocked-community:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/mrs/ru-blocked-community.mrs
    path: ./rule-sets/ru-blocked-community.mrs
    interval: 86400
  ru-blocked-domains:
    type: http
    behavior: domain
    format: text
    url: https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/ru-blocked.txt
    path: ./rule-sets/ru-blocked-domains.txt
    interval: 86400
  telegram:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/mrs/telegram.mrs
    path: ./rule-sets/telegram.mrs
    interval: 86400
  russia-inside:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/itdoginfo/allow-domains/releases/latest/download/russia_inside_domain.mrs
    path: ./rule-sets/russia-inside.mrs
    interval: 86400
  hodca:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/itdoginfo/allow-domains/releases/latest/download/hodca_domain.mrs
    path: ./rule-sets/hodca.mrs
    interval: 86400
  hydra-ru:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/master/release/mihomo/category-ru.mrs
    path: ./rule-sets/hydra-category-ru.mrs
    interval: 86400
  hydra-whitelist:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/master/release/mihomo/whitelist.mrs
    path: ./rule-sets/hydra-whitelist.mrs
    interval: 86400
  win-spy:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/master/release/mihomo/win-spy.mrs
    path: ./rule-sets/win-spy.mrs
    interval: 86400
  steam:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/master/release/mihomo/steam.mrs
    path: ./rule-sets/steam.mrs
    interval: 86400
  discord:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/itdoginfo/allow-domains/releases/latest/download/discord_ipcidr.mrs
    path: ./rule-sets/discord.mrs
    interval: 86400

rules:
  # BLOCK
  - RULE-SET,ads,REJECT
  - RULE-SET,win-spy,REJECT

    # Исключения для отдельных сервисов (из правил)
  #Youtube
  - RULE-SET,youtube,• YouTube
  #Telegram
  - PROCESS-NAME,Telegram.exe,• Telegram
  - PROCESS-NAME,AyuGram.exe,• Telegram
  - PROCESS-NAME,telegram,• Telegram
  - RULE-SET,telegram,• Telegram,no-resolve
  - DOMAIN-SUFFIX,stun.telegram.org,• Telegram # помогает со звонками при FakeIP
  #Discord
  - PROCESS-NAME,Discord.exe,• Discord
  - PROCESS-NAME,discord,• Discord
  - RULE-SET,discord,• Discord,no-resolve
  #Steam
  - PROCESS-NAME,Steam.exe,• Steam
  - RULE-SET,steam,• Steam

  # Proxy
  #*no-resolve - не резолвить домены для ip списков
    # Списки из правил legiz-ru
  - RULE-SET,ru-inline-banned,🌍 Блокированное
    # Списки из правил runetfreedom
  - RULE-SET,ru-blocked,🌍 Блокированное,no-resolve
  - RULE-SET,ru-blocked-community,🌍 Блокированное,no-resolve
  - RULE-SET,ru-blocked-domains,🌍 Блокированное
    # Списки из правил ItDog
  - RULE-SET,russia-inside,🌍 Блокированное
  - RULE-SET,hodca,🌍 Блокированное



  # DIRECT RUSSIA
    # Списки из правил legiz-ru
  - RULE-SET,ru-app-list,Россия # Приложения напрямую
  - RULE-SET,ru-inline,Россия # Сайты напрямую (не все)
    # От MetaCubeX
  - RULE-SET,geosite-ru,Россия
  - RULE-SET,geoip-ru,Россия,no-resolve
    # От Hydraponique
  - RULE-SET,hydra-ru,Россия # Банки и чекеры IP Макса
  - RULE-SET,hydra-whitelist,Россия # Ру сайты
    # Сайты
  - DOMAIN-SUFFIX,rule34.xxx,Россия
  - DOMAIN-SUFFIX,ntc.party,Россия

  #DIRECT Частные сети
    # От MetaCubeX
  - RULE-SET,geoip-private,Россия,no-resolve
  - RULE-SET,geosite-private,Россия

  # DIRECT Игры, Обновления и Торренты
    # От legiz-ru
  - RULE-SET,games-direct,Россия
  - RULE-SET,torrent-clients,Россия
  - RULE-SET,torrent-trackers,Россия
    # От MetaCubeX
  - RULE-SET,xiaomi,Россия
  - RULE-SET,blender,Россия
  - RULE-SET,drweb,Россия
  - RULE-SET,debian,Россия
  - RULE-SET,canonical,Россия
  - RULE-SET,python,Россия

   # Всё остальное
  - MATCH,🌐 Остальное

